name: traj
channels:
  - idaholab
  - conda-forge
  - defaults
dependencies:
  - antlr-python-runtime=4.7.2
  - appdirs=1.4.4
  - bokeh=2.2.3
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cartopy=0.18.0
  - certifi=2020.12.5
  - cf-units=2.1.4
  - cffi=1.14.4
  - cftime=1.3.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - cryptography=3.3.1
  - curl=7.71.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2020.12.0
  - dask-core=2020.12.0
  - distributed=2020.12.0
  - expat=2.2.9
  - freetype=2.10.4
  - fsspec=0.8.5
  - geos=3.8.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - idna=2.10
  - importlib-metadata=3.4.0
  - importlib_metadata=3.4.0
  - importlib_resources=5.0.0
  - ipython_genutils=0.2.0
  - iris=2.4.0
  - jinja2=2.11.2
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.11
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libcxx=11.0.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libnetcdf=4.7.4
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.1.0
  - llvm-openmp=11.0.0
  - locket=0.2.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib-base=3.3.3
  - metpy=1.0
  - msgpack-python=1.0.2
  - ncurses=6.2
  - netcdf4=1.5.5.1
  - numexpr=2.7.2
  - numpy=1.19.5
  - olefile=0.46
  - openssl=1.1.1i
  - packaging=20.8
  - pandas=1.2.0
  - partd=1.1.0
  - pillow=8.1.0
  - pint=0.16.1
  - pip=20.3.3
  - pooch=1.3.0
  - proj=7.2.0
  - psutil=5.8.0
  - pycparser=2.20
  - pyke=1.1.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=3.0.0.post1
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.8.6
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.5
  - pyyaml=5.3.1
  - readline=8.0
  - requests=2.25.1
  - scipy=1.6.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.15.0
  - sortedcontainers=2.3.0
  - sqlite=3.34.0
  - tblib=1.6.0
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - tzdata=2020f
  - udunits2=2.2.27.27
  - urllib3=1.26.2
  - wheel=0.36.2
  - xarray=0.16.2
  - xxhash=0.8.0
  - xz=5.2.5
  - yaml=0.2.5
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.8
  - pip:
    - aiohttp==3.7.3
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - ambiance==1.1.0
    - async-timeout==3.0.1
    - attrs==20.3.0
    - blessings==1.7
    - cachetools==4.2.0
    - chardet==3.0.4
    - colorama==0.4.4
    - colorful==0.5.4
    - eccodes-python==0.9.9
    - filelock==3.0.12
    - google-api-core==1.25.0
    - google-auth==1.24.0
    - googleapis-common-protos==1.52.0
    - gpustat==0.6.0
    - grpcio==1.34.1
    - hiredis==1.1.0
    - iris-grib==0.15.0
    - jsonschema==3.2.0
    - multidict==5.1.0
    - nvidia-ml-py3==7.352.0
    - opencensus==0.7.11
    - opencensus-context==0.1.2
    - prometheus-client==0.9.0
    - protobuf==3.14.0
    - py-spy==0.3.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyrsistent==0.17.3
    - ray==1.1.0
    - redis==3.5.3
    - rsa==4.7
    - yarl==1.6.3
